language: java
jdk:
  - openjdk11
services:
  - docker
before_install:
  - mvn -B versions:set -DnewVersion=$TRAVIS_BRANCH
script:
  - mvn -B package
  - docker build -t inseefrlab/adventofcodeleaderboard .
deploy:
  skip_cleanup: true
  provider: script
  script:
    echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    && docker push inseefrlab/adventofcodeleaderboard
  on:
    branch: master
env:
  global:
    - secure: CxalFRlQV+eAQAhoT4TLD9UxMlfGWWzLLle+PIm6YDNamkI3k9DJsbX2xnKDF2hXxUO6xC8m6hE2yeDD9uyA881i3RrWWWcOwFhLh0iurS0El7q9OzeAG99yyMIIyyUw3C5wIxrF9PO418Zs1/PvQlZ815Af4WNA0jFdwdWLkUX98WR7mJbM7xbPImXqs/vfPkAmZkEE9LRJ3kijyIkeO8MaCirXyp45V9ctb28vHL/Z+hKJxFBFyPxM5zP3hH0UGU1FzhQRaYdFd+MlWGjRMXe1rhIejqdJ4dcASyPOLtodvat8hWKddQzSQRtKfqfDCRcHc5PZoEgXww7dijWR34YR6DxEi88MybcG3tWUH8qWGmGa8AuubFm+DTtLUMDlOGOzaW9ZPBHvKib0T00o2tHqezwogdp8C9crxImjN5w7fb4+0Wk9dTdR5wZ5cnmP5zTkfmin1FF1u90gLFibiZny5icvQZ1UWmvDMzIitdSYS8H5FhrPhhF8Ja+TPxt4pmmJ8rcWGfj4FXpbX0/SadrAR+LChY1uhtEq/TxHxGcagqfJ5DgSHO7UW8HQB/LMDgx6OPUjv6+yt3hEaxFX/f4mpE+TolFNzzQ+QAN8R7yCHk4CK5MNJ2/sJOFCx41AMVXYZSkoWJmujVCjX4/4yIlILloAxzDSq77HOXjYF9M=
    - secure: Jh3oXz6arVCCyk3JRqdPfx0P8C5Nc44aAiKikufacW8HCn8DcIdGNZ6RJCqgERl8HiH9kCpp/VSwN/CJWEVfRGxIz06DqsphuYEaTx6bm7gvBgP4HqsapM3At9OjfaXTX6BF3M2aP/ibOsTCcTl0IOPqimq9cQg8f/q3KsSQCWkMcLvL6ut7u0XG5RiUAQhoryA44p8Xy0Ig9e9KcK6uzN9zixtncxSG7tIrGUvg5QT5htH+30Zi/5D5CIkkHXjQ4z3XeWRxTtmFuhIX3atSBRcdD2mAtmaiZel/Y3Sw/ye2iN4RHMMWpxJV7QyBcUWttNXcRx8KL02/fQ8vYICgH+tzd1qywHzS5ItWxFQBVZnXpcQJM9VQ9Du9V/ScZLBV7Dksa0m8+nw652KFpiPW2o3jm3+HGdDw15tI7chWZgad72IC0bc/RMK+aVXEe+aWL/yu9vIx/z7cNbCE1iJ9Mnff82ZuztOnGNeElyPsEiwgXinaSvCcDrp5RGjnRGYz/17ew5GfFOEzAkHDsYKGv4yDJ1BFAJArW6/yLrIH5JDkMOpAuSdWTK+ZlBH8bB4lf9qp1HMRsAb4yY9957XLs7Roi2f34/y7Cm3Svfzwq+3gtVQ9VMu8iEMQuNCEQv+TXEbcfY6zq7ST99lct00gXzrs++RexWWh6KAQ0CdrDMw=
